development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=mathmotion user=mathmotion password=mathmotion sslmode=disable
  dir: internal/repository/postgres/migrations
  table: migrations

production:
  dialect: postgres
  datasource: host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} user=${DB_USERNAME} password=${DB_PASSWORD} sslmode=disable
  dir: internal/repository/postgres/migrations
  table: migrations
